/* Generated By:JavaCC: Do not edit this line. AnalisiConstants.java */
package analisiProject;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalisiConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AND = 6;
  /** RegularExpression Id. */
  int OR = 7;
  /** RegularExpression Id. */
  int NOT = 8;
  /** RegularExpression Id. */
  int DIMENSOPER = 9;
  /** RegularExpression Id. */
  int OPERATOR = 10;
  /** RegularExpression Id. */
  int ogr = 11;
  /** RegularExpression Id. */
  int cgr = 12;
  /** RegularExpression Id. */
  int FOR = 13;
  /** RegularExpression Id. */
  int WHILE = 14;
  /** RegularExpression Id. */
  int IF = 15;
  /** RegularExpression Id. */
  int NULL = 16;
  /** RegularExpression Id. */
  int EXIT = 17;
  /** RegularExpression Id. */
  int INTEGER = 18;
  /** RegularExpression Id. */
  int END = 19;
  /** RegularExpression Id. */
  int OPENPAR = 20;
  /** RegularExpression Id. */
  int CLOSEPAR = 21;
  /** RegularExpression Id. */
  int EQUAL = 22;
  /** RegularExpression Id. */
  int COMMA = 23;
  /** RegularExpression Id. */
  int ANNCLASS = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"int\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "<DIMENSOPER>",
    "<OPERATOR>",
    "\"{\"",
    "\"}\"",
    "\"for\"",
    "<WHILE>",
    "\"if\"",
    "\"NULL\"",
    "\"EXIT\"",
    "<INTEGER>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\",\"",
    "<ANNCLASS>",
    "\"==\"",
  };

}
